apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "metrics-server"
  namespace: "argocd"
spec:
  destination:
    namespace: "metrics-server"
    server: "https://kubernetes.default.svc"
  project: "default"
  sources:
    - chart: "metrics-server"
      helm:
        valueFiles:
          - "$values/metrics-server/values.yaml"
      repoURL: "https://kubernetes-sigs.github.io/metrics-server"
      targetRevision: "3.13.0"
    - path: "metrics-server"
      ref: "values"
      repoURL: "https://github.com/deinok/TREBALL-INVESTIGACIO.git"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
