apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "otel"
  namespace: "argocd"
spec:
  destination:
    namespace: "otel"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    repoURL: https://charts.signoz.io
    targetRevision: 0.105.2
    chart: signoz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
