apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "otel"
  namespace: "argocd"
spec:
  destination:
    namespace: "otel"
    server: "https://kubernetes.default.svc"
  project: "default"
  sources:
    - repoURL: "https://charts.signoz.io"
      chart: "signoz"
      helm:
        valueFiles:
          - "$values/otel/values.yaml"
      targetRevision: "0.105.2"
    - repoURL: "https://github.com/deinok/TREBALL-INVESTIGACIO.git"
      ref: "values"
      targetRevision: "HEAD"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
